const Electronic = [
    {
      "actor": "Elon Musk",
      "song": "Don't Doubt ur Vibe",
      "genre": "Electronic",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/mink-mingle-HRyjETL87Gg-unsplash.jpg",
    },
    {
      "actor": "Idris Elba",
      "song": "Ballie",
      "genre": "Electronic/House",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/aditya-chinchure-ZhQCZjr9fHo-unsplash.jpg",
    },
    {
      "actor": "DJ Diesel (Shaquille O'Neal)",
      "song": "Bang Your Head",
      "genre": "Electronic/Dubstep",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/adrian-korte-5gn2soeAc40-unsplash.jpg",
    },
    {
      "actor": "Joe Keery (Djo)",
      "song": "Roddy",
      "genre": "Electronic/Indie",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/alex-padurariu-WypHPk6lBFQ-unsplash.jpg",
    },
    {
      "actor": "Milla Jovovich",
      "song": "Electric Sky",
      "genre": "Electronic",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/alexey-ruban-73o_FzZ5x-w-unsplash.jpg",
    },
    {
      "actor": "Donald Glover (Childish Gambino)",
      "song": "3005",
      "genre": "Electronic/Hip-Hop",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/alphacolor-66JMudIjDTw-unsplash.jpg",
    },
    {
      "actor": "Will Smith",
      "song": "Gettin' Jiggy Wit It (Remix)",
      "genre": "Electronic/Dance",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/andrew-neel-ute2XAFQU2I-unsplash.jpg",
    },
    {
      "actor": "Paris Hilton",
      "song": "Stars Are Blind",
      "genre": "Electronic/Pop",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/asli-yaren-peker-hebbKTxFID4-unsplash.jpg",
    },
    {
      "actor": "Jaden Smith",
      "song": "ICON",
      "genre": "Electronic/Hip-Hop",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/asli-yaren-peker-jlYZQYKRXSc-unsplash.jpg",
    },
    {
      "actor": "Kristen Stewart",
      "song": "With You (Remix)",
      "genre": "Electronic",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/asli-yaren-peker-UmPBfI248fU-unsplash.jpg",
    },
    {
      "actor": "Michael Cera",
      "song": "Too Much",
      "genre": "Electronic",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/austin-prock-Hz3Kjzgyv_Q-unsplash.jpg",
    },
    {
      "actor": "Vin Diesel",
      "song": "Feel Like I Do",
      "genre": "Electronic/Dance",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/clark-tibbs-oqStl2L5oxI-unsplash.jpg",
    },
    {
      "actor": "Eddie Murphy",
      "song": "Red Light (ft. Snoop Lion)",
      "genre": "Electronic/Reggae",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/claus-grunstaudl-dKeB0-M9iiA-unsplash.jpg",
    },
    {
      "actor": "Hugh Laurie",
      "song": "Mystery Train",
      "genre": "Electronic/Blues",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/clem-onojeghuo-Sgthj0HW6ec-unsplash.jpg",
    },
    {
      "actor": "Joaquin Phoenix",
      "song": "Scarlet Lights",
      "genre": "Electronic/Indie",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/diego-catto-DI6ywiG5N0g-unsplash.jpg",
    },
    {
      "actor": "Tom Hardy",
      "song": "Falling Rain",
      "genre": "Electronic",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/efe-kurnaz-RnCPiXixooY-unsplash.jpg",
    },
    {
      "actor": "Scarlett Johansson",
      "song": "Falling Down (Remix)",
      "genre": "Electronic/Indie",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/eric-nopanen-8e0EHPUx3Mo-unsplash.jpg",
    },
    {
      "actor": "Ansel Elgort",
      "song": "Thief",
      "genre": "Electronic",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/gabriel-gurrola-2UuhMZEChdc-unsplash.jpg",
    },
    {
      "actor": "Jeremy Renner",
      "song": "Main Attraction",
      "genre": "Electronic",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/israel-palacio-Y20JJ_ddy9M-unsplash.jpg",
    },
    {
      "actor": "Tilda Swinton",
      "song": "Strange Stars",
      "genre": "Electronic",
      "spotify_link": "/Audio/Alone_-_Color_Out.mp3",
      "img": "/Music/james-owen-c-NBiJrhwdM-unsplash.jpg",
    }
  ]
  export default Electronic