const Hiphop = [
    {
      "actor": "Childish Gambino (Donald Glover)",
      "song": "This Is America",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/jens-thekkeveettil-dBWvUqBoOU8-unsplash.jpg",
    },
    {
      "actor": "Drake",
      "song": "God's Plan",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/james-owen-c-NBiJrhwdM-unsplash.jpg",
    },
    {
      "actor": "Will Smith",
      "song": "Gettin' Jiggy Wit It",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/israel-palacio-Y20JJ_ddy9M-unsplash.jpg",
    },
    {
      "actor": "Queen Latifah",
      "song": "U.N.I.T.Y.",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/gabriel-gurrola-2UuhMZEChdc-unsplash.jpg",
    },
    {
      "actor": "LL Cool J",
      "song": "Mama Said Knock You Out",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/eric-nopanen-8e0EHPUx3Mo-unsplash.jpg",
    },
    {
      "actor": "Ice Cube",
      "song": "It Was a Good Day",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/efe-kurnaz-RnCPiXixooY-unsplash.jpg",
    },
    {
      "actor": "Ludacris",
      "song": "Stand Up",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/diego-catto-DI6ywiG5N0g-unsplash.jpg",
    },
    {
      "actor": "Tupac Shakur",
      "song": "California Love",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/clem-onojeghuo-Sgthj0HW6ec-unsplash.jpg",
    },
    {
      "actor": "Ice-T",
      "song": "Colors",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/claus-grunstaudl-dKeB0-M9iiA-unsplash.jpg",
    },
    {
      "actor": "Eve",
      "song": "Let Me Blow Ya Mind (feat. Gwen Stefani)",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/clark-tibbs-oqStl2L5oxI-unsplash.jpg",
    },
    {
      "actor": "Common",
      "song": "The Light",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/austin-prock-Hz3Kjzgyv_Q-unsplash.jpg",
    },
    {
      "actor": "T.I.",
      "song": "Live Your Life (feat. Rihanna)",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/asli-yaren-peker-UmPBfI248fU-unsplash.jpg",
    },
    {
      "actor": "Mos Def (Yasiin Bey)",
      "song": "Ms. Fat Booty",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/asli-yaren-peker-jlYZQYKRXSc-unsplash.jpg",
    },
    {
      "actor": "Jaden Smith",
      "song": "Icon",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/asli-yaren-peker-hebbKTxFID4-unsplash.jpg",
    },
    {
      "actor": "Method Man",
      "song": "Bring The Pain",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/andrew-neel-ute2XAFQU2I-unsplash.jpg",
    },
    {
      "actor": "50 Cent",
      "song": "In Da Club",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/alphacolor-66JMudIjDTw-unsplash.jpg",
    },
    {
      "actor": "Nick Cannon",
      "song": "Gigolo",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/alexey-ruban-73o_FzZ5x-w-unsplash.jpg",
    },
    {
      "actor": "Bow Wow",
      "song": "Like You (feat. Ciara)",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/alex-padurariu-WypHPk6lBFQ-unsplash.jpg",
    },
    {
      "actor": "Post Malone",
      "song": "Rockstar (feat. 21 Savage)",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/adrian-korte-5gn2soeAc40-unsplash.jpg",
    },
    {
      "actor": "Snoop Dogg",
      "song": "Drop It Like It's Hot",
      "genre": "Hip Hop",
      "spotify_link": "/Audio/LEEONA_-_LEEONA_-_Do_I.mp3",
      "img": "/Music/aditya-chinchure-ZhQCZjr9fHo-unsplash.jpg",
    }
  ]
  export default Hiphop;