const Pop = [
  {
    "actor": "Hailee Steinfeld",
    "song": "Love Myself",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/clark-tibbs-oqStl2L5oxI-unsplash.jpg",
  },
  {
    "actor": "Harry Styles",
    "song": "As It Was",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/claus-grunstaudl-dKeB0-M9iiA-unsplash.jpg",
  },
  {
    "actor": "Selena Gomez",
    "song": "Lose You to Love Me",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/clem-onojeghuo-Sgthj0HW6ec-unsplash.jpg",
  },
  {
    "actor": "Zendaya",
    "song": "Replay",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/diego-catto-DI6ywiG5N0g-unsplash.jpg",
  },
  {
    "actor": "Demi Lovato",
    "song": "Sorry Not Sorry",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/efe-kurnaz-RnCPiXixooY-unsplash.jpg",
  },
  {
    "actor": "Miley Cyrus",
    "song": "Flowers",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/eric-nopanen-8e0EHPUx3Mo-unsplash.jpg",
  },
  {
    "actor": "Ariana Grande",
    "song": "Positions",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/gabriel-gurrola-2UuhMZEChdc-unsplash.jpg",
  },
  {
    "actor": "Troye Sivan",
    "song": "Youth",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/israel-palacio-Y20JJ_ddy9M-unsplash.jpg",
  },
  {
    "actor": "Leighton Meester",
    "song": "Somebody to Love",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/james-owen-c-NBiJrhwdM-unsplash.jpg",
  },
  {
    "actor": "Bridgit Mendler",
    "song": "Ready or Not",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/jens-thekkeveettil-dBWvUqBoOU8-unsplash.jpg",
  },
  {
    "actor": "Ashley Tisdale",
    "song": "He Said She Said",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/john-matychuk-gUK3lA3K7Yo-unsplash.jpg",
  },
  {
    "actor": "Olivia Rodrigo",
    "song": "drivers license",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/kari-shea-laHwVPkMTzY-unsplash.jpg",
  },
  {
    "actor": "Jared Leto",
    "song": "Walk on Water",
    "genre": "Pop/Rock",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/kelly-sikkema-HwU5H9Y6aL8-unsplash.jpg",
  },
  {
    "actor": "Hilary Duff",
    "song": "Come Clean",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/lorenzo-spoleti-MlhJNEUQpBs-unsplash.jpg",
  },
  {
    "actor": "Justin Timberlake",
    "song": "Can't Stop the Feeling!",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/markus-spiske-hU9gx8YfVK4-unsplash.jpg",
  },
  {
    "actor": "Taylor Momsen",
    "song": "Make Me Wanna Die",
    "genre": "Pop/Rock",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/matheus-ferrero-r4TcI0Yo_rw-unsplash.jpg",
  },
  {
    "actor": "Keke Palmer",
    "song": "I Don't Belong to You",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/mink-mingle-HRyjETL87Gg-unsplash.jpg",
  },
  {
    "actor": "Nick Jonas",
    "song": "Jealous",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/saso-tusar-QtgGYlug6Cw-unsplash.jpg",
  },
  {
    "actor": "Jennifer Lopez",
    "song": "On The Floor",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/stefany-andrade-GbSCAAsU2Fo-unsplash.jpg",
  },
  {
    "actor": "Joe Jonas",
    "song": "Cake by the Ocean (DNCE)",
    "genre": "Pop",
    "spotify_link": "/Audio/Molotov_Heart_-_radionowhere.mp3",
    "img": "/Music/william-recinos-qtYhAQnIwSE-unsplash.jpg",
  }
];

export default Pop;